service: app
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
