service: app
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  region: ap-northeast-1

functions:
  hello:
    name: sample-project
    timeout: 900
    image: <ACCOUNT_ID>.dkr.ecr.ap-northeast-1.amazonaws.com/example-python:latest
    events:
      - httpApi:
          path: /
          method: get